config/routes.rb
Rails.application.routes.draw do
  resources :contatcs
  resources :annotations
   root "welcome#index"
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/annotation.rb
class Annotation < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contatc.rb
class Contatc < ApplicationRecord
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :set_annotation, only: %i[ show edit update destroy ]

  # GET /annotations or /annotations.json
  def index
    @annotations = Annotation.all.paginate(page: params[:page], per_page: 5)
  end

  # GET /annotations/1 or /annotations/1.json
  def show
  end

  # GET /annotations/new
  def new
    @annotation = Annotation.new
  end

  # GET /annotations/1/edit
  def edit
  end

  # POST /annotations or /annotations.json
  def create
    @annotation = Annotation.new(annotation_params)

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to annotation_url(@annotation), notice: "Annotation was successfully created." }
        format.json { render :show, status: :created, location: @annotation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annotations/1 or /annotations/1.json
  def update
    respond_to do |format|
      if @annotation.update(annotation_params)
        format.html { redirect_to annotation_url(@annotation), notice: "Annotation was successfully updated." }
        format.json { render :show, status: :ok, location: @annotation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1 or /annotations/1.json
  def destroy
    @annotation.destroy

    respond_to do |format|
      format.html { redirect_to annotations_url, notice: "Annotation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def annotation_params
      params.require(:annotation).permit(:body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contatcs_controller.rb
class ContatcsController < ApplicationController
  before_action :set_contatc, only: %i[ show edit update destroy ]

  # GET /contatcs or /contatcs.json
  def index
    @contatcs = Contatc.all.paginate(page: params[:page], per_page: 5)
    
  end

  # GET /contatcs/1 or /contatcs/1.json
  def show
  end

  # GET /contatcs/new
  def new
    @contatc = Contatc.new
  end

  # GET /contatcs/1/edit
  def edit
  end

  # POST /contatcs or /contatcs.json
  def create
    @contatc = Contatc.new(contatc_params)

    respond_to do |format|
      if @contatc.save
        format.html { redirect_to contatc_url(@contatc), notice: "Contatc was successfully created." }
        format.json { render :show, status: :created, location: @contatc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contatc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatcs/1 or /contatcs/1.json
  def update
    respond_to do |format|
      if @contatc.update(contatc_params)
        format.html { redirect_to contatc_url(@contatc), notice: "Contatc was successfully updated." }
        format.json { render :show, status: :ok, location: @contatc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contatc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatcs/1 or /contatcs/1.json
  def destroy
    @contatc.destroy

    respond_to do |format|
      format.html { redirect_to contatcs_url, notice: "Contatc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contatc
      @contatc = Contatc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contatc_params
      params.require(:contatc).permit(:name, :address, :email, :phone)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatcs_helper.rb
module ContatcsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/annotations/_annotation.html.erb
<div id="<%= dom_id annotation %>">
  <p>
    <strong>Body:</strong>
    <%= annotation.body %>
  </p>

</div>

app/views/annotations/_form.html.erb
<%= form_for @annotation, :html => { :class => "form-horizontal annotation" } do |f| %>

  <% if @annotation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@annotation.errors.count, "error") %> prohibited this annotation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @annotation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :body, :class => 'form-control' %>
    </div>
    <%=f.error_span(:body) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                annotations_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/annotations/edit.html.erb
<%- model_class = Annotation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/annotations/index.html.erb
<%- model_class = Annotation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><%= link_to annotation.id, annotation_path(annotation) %></td>
        <td><%= annotation.body %></td>
        <td><%=l annotation.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      annotation_path(annotation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_annotation_path(annotation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      annotation_path(annotation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_annotation_path,
            :class => 'btn btn-primary' %>

<%= will_paginate @annotation%>

app/views/annotations/new.html.erb
<%- model_class = Annotation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/annotations/show.html.erb
<%- model_class = Annotation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @annotation.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              annotations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_annotation_path(@annotation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              annotation_path(@annotation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/contatcs/_contatc.html.erb
<div id="<%= dom_id contatc %>">
  <p>
    <strong>Name:</strong>
    <%= contatc.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= contatc.address %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contatc.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contatc.phone %>
  </p>

</div>

app/views/contatcs/_form.html.erb
<%= form_for @contatc, :html => { :class => "form-horizontal contatc" } do |f| %>

  <% if @contatc.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@contatc.errors.count, "error") %> prohibited this contatc from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @contatc.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                contatcs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/contatcs/edit.html.erb
<%- model_class = Contatc -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contatcs/index.html.erb
<%- model_class = Contatc -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      
     
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contatcs.each do |contatc| %>
      <tr>
        <td><%= link_to contatc.id, contatc_path(contatc) %></td>
        <td><%= contatc.name %></td>
      
        <td><%= contatc.phone %></td>
        <td><%=l contatc.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      contatc_path(contatc), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contatc_path(contatc), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contatc_path(contatc),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contatc_path,
            :class => 'btn btn-success' %>

<%= will_paginate @contatc%>

app/views/contatcs/new.html.erb
<%- model_class = Contatc -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contatcs/show.html.erb
<%- model_class = Contatc -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @contatc.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @contatc.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @contatc.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @contatc.phone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              contatcs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_contatc_path(@contatc), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contatc_path(@contatc),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Remember" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
   
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
   
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class=" conteiner bg-dark">
      <div class="container-fluid nav-collapse">
       
        <h2><a class="navbar-brand text-white" href="#">Remember</a></h2>
        
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
      <div class="col-lg-3">
          <div class="well sidebar-nav bg-light">
            <h3>Sidebar</h3>
            <ul class="nav flex-column">
              
              <div class="nav-link">
                  <li><%= link_to "Início", root_path  %></li>
              </div>
              <div class="nav-link">
                   <li><%= link_to "Anotações", annotations_path  %></li>
              </div>
               <div class="nav-link">
                   <li><%= link_to "Contatos", contatcs_path  %></li>
              </div>
             
            </ul>
          </div><!--/.well -->
        </div><!--/span-->

        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2023</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1 class = "btn btn-success">Remember</h1>
<p>Seja bem vindo a sua agenda pessoal!</p>